### ISSUE TITLE
Italic Guidelines are shifted right

### ISSUE THREAD

**Issue by impallari** [impallari/Unitizer#4]
Italics guidelines are shifted right, outside the glyph zone. They need to be moved to the correct position
![screen shot 2016-04-29 at 14 17 31](https://cloud.githubusercontent.com/assets/3036973/14923806/c2a8553e-0e15-11e6-85ae-f2e7cb998a41.png)
Guys, I need help with this! @simoncozens @mekkablue @Tosche @Mark2Mark @justanotherfoundry @guidoferreyra @Nevu

**Comment by simoncozens** [comment]
The problem is that, in Glyphs, the origin of the X-axis is not at the intersection of the baseline and the left-hand-side, as you would expect. It's actually half way between the baseline and the x-height, which in a slanted master means that the lines need to start at a different place:

![screen shot 2016-04-30 at 11 06 54](https://cloud.githubusercontent.com/assets/106728/14932971/bc7c097c-0ec3-11e6-973e-b632931350cd.png)
